/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.michalklempa.avro.schemas.common;
/** Department enum */
@org.apache.avro.specific.AvroGenerated
public enum Department implements org.apache.avro.generic.GenericEnumSymbol<Department> {
  FRONTEND, BACKEND, DATABASE, ADMIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Department\",\"namespace\":\"com.michalklempa.avro.schemas.common\",\"doc\":\"Department enum\",\"symbols\":[\"FRONTEND\",\"BACKEND\",\"DATABASE\",\"ADMIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
