/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.michalklempa.avro.schemas.common;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** GPS */
@org.apache.avro.specific.AvroGenerated
public class GPS extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6638213802079674781L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GPS\",\"namespace\":\"com.michalklempa.avro.schemas.common\",\"doc\":\"GPS\",\"fields\":[{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GPS> ENCODER =
      new BinaryMessageEncoder<GPS>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GPS> DECODER =
      new BinaryMessageDecoder<GPS>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GPS> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GPS> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GPS> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GPS>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GPS to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GPS from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GPS instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GPS fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double lat;
  @Deprecated public double lon;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GPS() {}

  /**
   * All-args constructor.
   * @param lat The new value for lat
   * @param lon The new value for lon
   */
  public GPS(java.lang.Double lat, java.lang.Double lon) {
    this.lat = lat;
    this.lon = lon;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return lat;
    case 1: return lon;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: lat = (java.lang.Double)value$; break;
    case 1: lon = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'lat' field.
   * @return The value of the 'lat' field.
   */
  public double getLat() {
    return lat;
  }


  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(double value) {
    this.lat = value;
  }

  /**
   * Gets the value of the 'lon' field.
   * @return The value of the 'lon' field.
   */
  public double getLon() {
    return lon;
  }


  /**
   * Sets the value of the 'lon' field.
   * @param value the value to set.
   */
  public void setLon(double value) {
    this.lon = value;
  }

  /**
   * Creates a new GPS RecordBuilder.
   * @return A new GPS RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.GPS.Builder newBuilder() {
    return new com.michalklempa.avro.schemas.common.GPS.Builder();
  }

  /**
   * Creates a new GPS RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GPS RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.GPS.Builder newBuilder(com.michalklempa.avro.schemas.common.GPS.Builder other) {
    if (other == null) {
      return new com.michalklempa.avro.schemas.common.GPS.Builder();
    } else {
      return new com.michalklempa.avro.schemas.common.GPS.Builder(other);
    }
  }

  /**
   * Creates a new GPS RecordBuilder by copying an existing GPS instance.
   * @param other The existing instance to copy.
   * @return A new GPS RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.GPS.Builder newBuilder(com.michalklempa.avro.schemas.common.GPS other) {
    if (other == null) {
      return new com.michalklempa.avro.schemas.common.GPS.Builder();
    } else {
      return new com.michalklempa.avro.schemas.common.GPS.Builder(other);
    }
  }

  /**
   * RecordBuilder for GPS instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GPS>
    implements org.apache.avro.data.RecordBuilder<GPS> {

    private double lat;
    private double lon;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.michalklempa.avro.schemas.common.GPS.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.lat)) {
        this.lat = data().deepCopy(fields()[0].schema(), other.lat);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lon)) {
        this.lon = data().deepCopy(fields()[1].schema(), other.lon);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GPS instance
     * @param other The existing instance to copy.
     */
    private Builder(com.michalklempa.avro.schemas.common.GPS other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.lat)) {
        this.lat = data().deepCopy(fields()[0].schema(), other.lat);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lon)) {
        this.lon = data().deepCopy(fields()[1].schema(), other.lon);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'lat' field.
      * @return The value.
      */
    public double getLat() {
      return lat;
    }


    /**
      * Sets the value of the 'lat' field.
      * @param value The value of 'lat'.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.GPS.Builder setLat(double value) {
      validate(fields()[0], value);
      this.lat = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'lat' field has been set.
      * @return True if the 'lat' field has been set, false otherwise.
      */
    public boolean hasLat() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'lat' field.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.GPS.Builder clearLat() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lon' field.
      * @return The value.
      */
    public double getLon() {
      return lon;
    }


    /**
      * Sets the value of the 'lon' field.
      * @param value The value of 'lon'.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.GPS.Builder setLon(double value) {
      validate(fields()[1], value);
      this.lon = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lon' field has been set.
      * @return True if the 'lon' field has been set, false otherwise.
      */
    public boolean hasLon() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lon' field.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.GPS.Builder clearLon() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GPS build() {
      try {
        GPS record = new GPS();
        record.lat = fieldSetFlags()[0] ? this.lat : (java.lang.Double) defaultValue(fields()[0]);
        record.lon = fieldSetFlags()[1] ? this.lon : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GPS>
    WRITER$ = (org.apache.avro.io.DatumWriter<GPS>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GPS>
    READER$ = (org.apache.avro.io.DatumReader<GPS>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.lat);

    out.writeDouble(this.lon);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.lat = in.readDouble();

      this.lon = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.lat = in.readDouble();
          break;

        case 1:
          this.lon = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










