/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.michalklempa.avro.schemas.common;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Location, includes union of two subtypes and one primitive type- string */
@org.apache.avro.specific.AvroGenerated
public class Location extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5740126001639375211L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Location\",\"namespace\":\"com.michalklempa.avro.schemas.common\",\"doc\":\"Location, includes union of two subtypes and one primitive type- string\",\"fields\":[{\"name\":\"locationSpec\",\"type\":[{\"type\":\"record\",\"name\":\"GPS\",\"doc\":\"GPS\",\"fields\":[{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]},{\"type\":\"string\",\"avro.java.string\":\"String\"},{\"type\":\"record\",\"name\":\"Address\",\"doc\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Location> ENCODER =
      new BinaryMessageEncoder<Location>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Location> DECODER =
      new BinaryMessageDecoder<Location>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Location> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Location> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Location> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Location>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Location to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Location from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Location instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Location fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Object locationSpec;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Location() {}

  /**
   * All-args constructor.
   * @param locationSpec The new value for locationSpec
   */
  public Location(java.lang.Object locationSpec) {
    this.locationSpec = locationSpec;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return locationSpec;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: locationSpec = value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'locationSpec' field.
   * @return The value of the 'locationSpec' field.
   */
  public java.lang.Object getLocationSpec() {
    return locationSpec;
  }


  /**
   * Sets the value of the 'locationSpec' field.
   * @param value the value to set.
   */
  public void setLocationSpec(java.lang.Object value) {
    this.locationSpec = value;
  }

  /**
   * Creates a new Location RecordBuilder.
   * @return A new Location RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.Location.Builder newBuilder() {
    return new com.michalklempa.avro.schemas.common.Location.Builder();
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Location RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.Location.Builder newBuilder(com.michalklempa.avro.schemas.common.Location.Builder other) {
    if (other == null) {
      return new com.michalklempa.avro.schemas.common.Location.Builder();
    } else {
      return new com.michalklempa.avro.schemas.common.Location.Builder(other);
    }
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Location instance.
   * @param other The existing instance to copy.
   * @return A new Location RecordBuilder
   */
  public static com.michalklempa.avro.schemas.common.Location.Builder newBuilder(com.michalklempa.avro.schemas.common.Location other) {
    if (other == null) {
      return new com.michalklempa.avro.schemas.common.Location.Builder();
    } else {
      return new com.michalklempa.avro.schemas.common.Location.Builder(other);
    }
  }

  /**
   * RecordBuilder for Location instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Location>
    implements org.apache.avro.data.RecordBuilder<Location> {

    private java.lang.Object locationSpec;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.michalklempa.avro.schemas.common.Location.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.locationSpec)) {
        this.locationSpec = data().deepCopy(fields()[0].schema(), other.locationSpec);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Location instance
     * @param other The existing instance to copy.
     */
    private Builder(com.michalklempa.avro.schemas.common.Location other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.locationSpec)) {
        this.locationSpec = data().deepCopy(fields()[0].schema(), other.locationSpec);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'locationSpec' field.
      * @return The value.
      */
    public java.lang.Object getLocationSpec() {
      return locationSpec;
    }


    /**
      * Sets the value of the 'locationSpec' field.
      * @param value The value of 'locationSpec'.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.Location.Builder setLocationSpec(java.lang.Object value) {
      validate(fields()[0], value);
      this.locationSpec = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'locationSpec' field has been set.
      * @return True if the 'locationSpec' field has been set, false otherwise.
      */
    public boolean hasLocationSpec() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'locationSpec' field.
      * @return This builder.
      */
    public com.michalklempa.avro.schemas.common.Location.Builder clearLocationSpec() {
      locationSpec = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Location build() {
      try {
        Location record = new Location();
        record.locationSpec = fieldSetFlags()[0] ? this.locationSpec :  defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Location>
    WRITER$ = (org.apache.avro.io.DatumWriter<Location>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Location>
    READER$ = (org.apache.avro.io.DatumReader<Location>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










